### ISSUE TITLE
退出客户端的时候ipfs进程并没有退出

### ISSUE THREAD

**Issue by cosin2077** [zy445566/ipfs-desktop#1]

**Comment by zy445566** [comment]
嗯，已确认，将会尽快修复，感谢反馈。欢迎提交PR

**Comment by zy445566** [comment]
@conanskyforce 
最新的release包已经解决了这个问题，但原来已经启动的ipfs进程可能要自己杀死
https://github.com/zy445566/ipfs-desktop/releases
